name: Run My Script
on: push
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run hello.py
        run: python hello.py
